name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
      - name: Build
        run: go build -race -v ./...
      - name: Test
        run: go test -race -v ./...